### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by TheEntropyShard** [betacraftuk/beta-c#1]
Not sure if this is problem of this program, but when I try to run compiled program on Windows 10 I get 0x000007b error.

I am compiling with this command:
`gcc -IC:\Users\Yura\Desktop\rd_132211_c -I"E:\Program Files (x86)\Embarcadero\Dev-Cpp\TDM-GCC-64\x86_64-w64-mingw32\include" -I"E:\Program Files (x86)\Embarcadero\Dev-Cpp\TDM-GCC-64\x86_64-w64-mingw32\include\SDL2" RubyDung.c HitResult.c Player.c Textures.c Timer.c Util.c level\Chunk.c level\Frustum.c level\Level.c level\LevelRenderer.c level\Tesselator.c level\Tile.c phys\AABB.c -o RubyDung.exe -lSDL2 -lSDL2_image -lz -lopengl32 -lglu32`

Output of `gcc -v`:
`Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=E:/Program\ Files\ (x86)/Embarcadero/Dev-Cpp/TDM-GCC-64/bin/../libexec/gcc/x86_64-w64-mingw32/9.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../../../src/gcc-git-9.2.0/configure --build=x86_64-w64-mingw32 --enable-targets=all --enable-languages=ada,c,c++,fortran,lto,objc,obj-c++ --enable-libgomp --enable-lto --enable-graphite --enable-cxx-flags=-DWINPTHREAD_STATIC --disable-build-with-cxx --disable-build-poststage1-with-cxx --enable-libstdcxx-debug --enable-threads=posix --enable-version-specific-runtime-libs --enable-fully-dynamic-string --enable-libstdcxx-threads --enable-libstdcxx-time --with-gnu-ld --disable-werror --disable-nls --disable-win32-registry --enable-large-address-aware --disable-rpath --disable-symvers --prefix=/mingw64tdm --with-local-prefix=/mingw64tdm --with-pkgversion=tdm64-1 --with-bugurl=http://tdm-gcc.tdragon.net/bugs
Thread model: posix
gcc version 9.2.0 (tdm64-1)`

I know that I can just go and play Java version, but it is interesting to try C version! :)

**Comment by win20-official** [comment]
You need to use cmake not just straight out gcc compiling it

**Comment by TheEntropyShard** [comment]
@win20-official Maybe, I am not a C programmer but a Java. It is so damn obscure and complicated to program in C on windows without Visual Studio. There is a thing call nob (nobuild) made by Tsoding. Maybe developers of beta-c should try it? :)

When I wrote this issue I was struggling to compile this project on Windows using CMake. I was getting so many linker errors. I know, it is my skill issue, but, why should it be so hard to simply compile a project consisting of a few C source files and two libraries?

**Comment by TheEntropyShard** [comment]
Well... I actually compiled it correctly, it just needed zlib1.dll to be placed near the executable... Works fine now
